project:
  type: website

website:
  title: "Reproducibility at Urban"
  site-url: https://ui-research.github.io/reproducibility-at-urban/

  page-footer: 
    border: true
    center: "This site is built with [Quarto](https://quarto.org/).<br>We welcome feedback and contributions through [GitHub](https://github.com/UI-Research/reproducibility-at-urban)." 
  navbar:
    left:
      - text: "Git & GitHub"
        menu:
        - href: git-overview.qmd
          text: Overview 
        - href: git-installation.qmd
          text: Access & Installation
        - href: git-workflow.qmd
          text: General Workflow
        - href: git-y-drive.qmd
          text: Confidential Data Workflow 
        - href: git-faqs.qmd
          text: FAQs & Other Resources 
      - href: virtual-environments.qmd
        text: Virtual Environments
      - href: quarto.qmd
        text: Quarto 
      - href: resources.qmd
        text: Additional Resources 
    right: 
      - icon: github
        href: https://github.com/UI-Research/reproducibility-at-urban

format:
  html:
    css: styles.css
    toc: true
    number-sections: true

execute:
  freeze: auto