project:
  type: website

website:
  title: "Reproducibility at Urban"
  navbar:
    left:
      - text: "Git & GitHub"
        menu:
        - href: git-overview.qmd
          text: Overview 
        - href: git-installation.qmd
          text: Access & Installation
        - href: git-workflow.qmd
          text: General Workflow
        - href: git-y-drive.qmd
          text: Confidential Data Workflow 
        - href: git-faqs.qmd
          text: FAQs & Other Resources 
      - href: virtual-environments.qmd
        text: Virtual Environments
      - href: quarto.qmd
        text: Quarto 
      - href: resources.qmd
        text: Additional Resources 

format:
  html:
    css: styles.css
    toc: true
    number-sections: true
