project:
  type: website
  output-dir: docs

website:
  title: "Reproducibility at Urban"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Git/Github"
        menu:
        - href: git-installation/git-installation.qmd
          text: Git Installation
        - href: urbngit/urbngit.qmd
          text: Git and Github
        - href: y-drive/y-drive.qmd
          text: Git and Github on the Y Drive
      - href: virtual-envs/virtual-envs.qmd
        text: Virtual Environments

format:
  html:
    css: styles.css
    toc: true
