project:
  type: website

website:
  title: "Reproducibility at Urban"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: urbngit.qmd
        text: Git and Github

format:
  html:
    #theme: cosmo
    css: styles.scss
    toc: true

editor: visual

