project:
  type: website

website:
  title: "Reproducibility at Urban"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: git-installation/git-installation.qmd
        text: Git Installation
      - href: urbngit/urbngit.qmd
        text: Git and Github

format:
  html:
    css: styles.css
    toc: true
